---
  - name: "LOOPBACK CONFIG WITH JINJA TEMPLATE"
    hosts: "nxos"
    tasks:

      - name: "ENSURE CONFIG DIR EXISTS"
        ansible.builtin.file:
          path: "config/loopbacks"
          state: "directory"
          mode: 0775
        run_once: true

      - name: "BUILD IOS INTERFACE CONFIG"
        ansible.builtin.template:
          src: "ios_interface.j2"
          dest: "config/loopbacks/{{ inventory_hostname }}_interface_config.txt"

      - name: "PUSH Config to Devices "
        cisco.nxos.nxos_config:
          src: "config/loopbacks/{{ inventory_hostname }}_interface_config.txt"
          backup: "yes"
          save_when: "modified"